name: Generate and Commit Resume PDF

on:
  push:
    branches:
      - main  # Change this to your default branch if needed
  workflow_dispatch:

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # This is required to push back to the repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "v2.x"

      - name: Generate resume.pdf
        run: deno run -A ./scripts/resume.ts

      - name: Commit and push updated resume.pdf
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add resume.pdf
          git commit -m "chore: update resume.pdf [auto]" || echo "No changes to commit"
          git push
